export { default as Package } from "./AddPackage/AddPackage";
export { default as SignInScreen } from "./SignInScreen";
export { default as SignUpScreen } from "./SignupScreen";
export { default as Appointment } from "./Appointment/Appointment";
export { default as Job} from "./AddJob/AddJob";
export { default as Service} from "./AddService/AddService";
export { default as BabyCare} from "./CategoriesOfServices/BabyCare";
export { default as Bleach} from "./CategoriesOfServices/Bleach";
export { default as Facial} from "./CategoriesOfServices/Facial";
export { default as HairColor} from "./CategoriesOfServices/HairColor";
export { default as HairCutting} from "./CategoriesOfServices/HairCutting";
export { default as HairStyling} from "./CategoriesOfServices/HairStyling";
export { default as HairTreatment} from "./CategoriesOfServices/HairTreatment";
export { default as Makeup} from "./CategoriesOfServices/Makeup";
export { default as Manicure} from "./CategoriesOfServices/Manicure";
export { default as Massage} from "./CategoriesOfServices/Massage";
export { default as Pedicure} from "./CategoriesOfServices/Pedicure";
export { default as Scrub} from "./CategoriesOfServices/Scrub";
export { default as Threading} from "./CategoriesOfServices/Threading";
export { default as Waxing} from "./CategoriesOfServices/Waxing";
export { default as CustomerRequest} from "./CustomerRequest/CustomerRequest";
export { default as ForgotPassword} from "./ForgotPassword/ForgotPassword";
export { default as JobSeekerRecruited} from "./JobSeekerRecruited/JobSeekerRecruited";
export { default as ManageStaff} from "./ManageStaff/ManageStaff";
export { default as SalonDetails} from "./SalonDetails/SalonDetails";
export { default as SalonHome} from "./SalonHome/SalonHome";
export { default as UpdatePassword} from "./UpdatePassword/UpdatePassword";
export { default as VerificationCode} from "./VerificationCode/VerificationCode";